class crc8:
    digest_size: int
    block_size: int
    def __init__(
        self, initial_string: bytes = ..., initial_start: int = ...
    ) -> None: ...
    def update(self, bytes_: bytes) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> crc8: ...
    def reset(self) -> None: ...
