[package]
name = "msgpacketizer"
version = "0.1.0"
edition = "2021"

[dependencies]
packetizer = { path = "../packetizer" }
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.3"
log = "0.4"

[dev-dependencies]
env_logger = "0.11"
