class crc8:
    digest_size: int
    block_size: int
    def __init__(self, initial_string: bytes = ..., initial_start: int = ...) -> None: ...
    def update(self, bytes_) -> None: ...
    def digest(self): ...
    def hexdigest(self): ...
    def copy(self): ...
    def reset(self) -> None: ...
